### ISSUE TITLE
After exiting out of mGBA and loading other content, RetroArch crashes.

### ISSUE THREAD

**Issue by IdiotBlueMage** [libretro/mgba#199] opened 2020-09-23 01:14 UTC
This happens every time without fail, and only happens after I use mGBA.

1. Start a game that uses mGBA
2. Close Content
3. Start another game from any core, it can even be the same game.
4. RetroArch crashes.

I'm using the Android version here.

**Comment by demodanza** [comment] 2020-10-01 01:32
I can confirm this, testing on Mipad 4 tablet, even when closing a ROM and loading the same one again, retroarch crashes. I'm attaching a log:
[retroarch.log](https://github.com/libretro/mgba/files/5309009/retroarch.log)

**Comment by endrift** [comment] 2020-10-01 01:59
This doesn't happen on Linux, so I assume something in upstream Retroarch broke on Android only and the effect is filtering down to mGBA. I don't think anything relevant would have changed here, but I don't have a way to debug this given I don't do Android development.

**Comment by Ryunam** [comment] 2020-10-23 16:23
I can confirm this does not happen on Windows 10 either.

**Comment by raidenii** [comment] 2020-12-04 01:15
Commit 20f007c works fine and commit b485ee7 is known to have issue. Don't have Android SDK to bisect which commit exactly caused the issue, though.

**Comment by endrift** [comment] 2020-12-04 02:02
If I had to take a guess it's crashing trying to interface with the sensor API, which I guess isn't particularly well tested. That would be consistent with what happened with the camera API too.

**Comment by raidenii** [comment] 2020-12-04 02:37
Libretro buildbot is compiling this pretty frequently, so testing whether it crashes should be relatively easy. Sensor/Camera API however, I don't know which game to use to test. Suggestions?

**Comment by endrift** [comment] 2020-12-04 02:39
Doesn't particularly matter, since the crash happens pretty much any game it seems. I can discuss testing more if I file a PR though.

**Comment by Littlemac123** [comment] 2020-12-21 19:44
I can consistently crash mGBA when still running a game from a android 7 OS on 32bit
just go to a different app, then go back to retroarch, then back to the app again, then ones you go back to retroarch it crashes the 2nt time every damn time, no other core does this.

sucks cuz that means i cant play pokemon wile texting someone

**Comment by IdiotBlueMage** [comment] 2021-01-02 15:56
Looks like this is all fixed on my end.  Thanks a billion!

I guess on that note, this issue is closed.

**Comment by Littlemac123** [comment] 2021-01-04 10:27
> I can consistently crash mGBA when still running a game from a android 7 OS on 32bit
> just go to a different app, then go back to retroarch, then back to the app again, then ones you go back to retroarch it crashes the 2nt time every damn time, no other core does this.
> 
> sucks cuz that means i cant play pokemon wile texting someone

this bug still happens for me however it might not be related to the bug happening up there but it is a crash

**Comment by raidenii** [comment] 2021-01-04 15:02
@Littlemac123 the buildbot version is not updated yet, still pending this PR to be merged: https://github.com/libretro/mgba/pull/218

**Comment by cor094** [comment] 2021-02-25 14:51
This issue is still happening to me on the latest mgba core on my Shield TV Pro retroarch 1.90 x64.

**Comment by twinaphex** [comment] 2021-02-25 14:59
I will reopen this issue considering the reports that say this is still happening.

**Comment by Dantasstic** [comment] 2021-03-21 00:49
Can we get an older working build of the mGBA core made available to us until this issue is fixed? [Apparently the 0.8.3 20f007c build of it works](https://www.reddit.com/r/RetroArch/comments/ioui97/mgba_latest_core_crash_retroarch_on_android/), but I am unable to find it anywhere. 

I can also confirm this issue occurring on both a GPD XD+ running Android 7.0 and a Pixel 3 XL running Android 11.0

**Comment by endrift** [comment] 2021-03-21 00:51
fwiw @twinaphex told me he'd provide me some crash logs since I don't have an Android workflow locally but I'm still waiting on those.

**Comment by Dantasstic** [comment] 2021-03-21 01:35
> 
> 
> fwiw @twinaphex told me he'd provide me some crash logs since I don't have an Android workflow locally but I'm still waiting on those.

If I can provide them, do let me know

**Comment by endrift** [comment] 2021-03-21 01:38
The biggest problem is that this needs a debug build to get enough debugging information, and I'm not 100% sure how to make those. Looking back at my chat with @twinaphex it seems it was left at him saying he'd see if he can reproduce it and me asking for a line number, but there's been no followup since then.

**Comment by Dantasstic** [comment] 2021-03-21 01:42
Yeah, it's super easy to reproduce. All you need is any Android device, RetroArch, a GBA ROM and the mGBA core haha

**Comment by endrift** [comment] 2021-03-21 03:08
I pulled out an old Android device I use almost never and let it charge. Hilariously, using the latest version of RA from the Play Store (1.9.0 I think?) and the latest mGBA core it no longer crashes for me, but before I updated RA it would crash. Even clearing the cache and everything it still won't crash, so I'm not sure.

**Comment by Dantasstic** [comment] 2021-03-21 03:11
Can you try it on the APK from the buildbot? That is what I am using, because I have zero interest in using the Play Store version.

https://buildbot.libretro.com/stable/1.9.0/android/RetroArch.apk

**Comment by endrift** [comment] 2021-03-21 05:19
Ok, I got it figured out.

The bug was fixed, months ago, in https://github.com/libretro/RetroArch/commit/34e08a688f165338550153db5f334a15fd891619. It's not an mGBA bug.

I hope next time someone actually affiliated with RetroArch does the legwork on these instead of me...

**Closed by endrift** 2021-03-21 05:19 UTC

**Comment by Dantasstic** [comment] 2021-03-21 05:30
....errr, that doesn't help with my issue though. How do I fix this?

> 
> 
> Ok, I got it figured out.
> 
> The bug was fixed, months ago, in [libretro/RetroArch@34e08a6](https://github.com/libretro/RetroArch/commit/34e08a688f165338550153db5f334a15fd891619). It's not an mGBA bug.
> 
> I hope next time someone actually affiliated with RetroArch does the legwork on these instead of me...

**Comment by endrift** [comment] 2021-03-21 05:31
You download a RetroArch nightly or wait for RetroArch 1.9.1 to come out. I don't have an old build since I'm not affiliated with RetroArch, I'm the author of the emulator itself. And the bug isn't in the emulator.

**Comment by Dantasstic** [comment] 2021-03-21 05:36
So, what you are saying is the RetroArch 1.9.0 Stable is not actually stable with mGBA. Gotcha! XD

So why did an earlier build of it work with 1.9.0 stable then, if it is not related to the mGBA core at all? Specifically build 0.8.3 20f007c

If RetroArch stable hasn't changed from 1.9.0 in a long time, then something that change in the mGBA core from the last working build to now is the change, correct?

**Comment by endrift** [comment] 2021-03-21 05:38
Yes, mGBA started using sensors exposed by RetroArch for a handful of games, like Kirby Tilt n Tumble, that work by tilting the device. Turns out the code that cleans up after sensors have been queried was buggy and crashes.

**Comment by Dantasstic** [comment] 2021-03-21 05:40
I see. It only seems to crash the android stable though, not Windows or linux handheld based ones from my testing

Ok, guess I will need to run the stupid Play Store version of RetroArch....that sucks

**Comment by endrift** [comment] 2021-03-21 05:41
No, the Play Store version not crashing may have been a fluke. I'd recommend a nightly instead.

The reason it doesn't crash on Windows or Linux is that the buggy code is specifically in their Android platform support.

**Comment by Dantasstic** [comment] 2021-03-21 05:43
Ok, I've just had major issues with nightlies before, which is why I've stuck with stable for the last while. Hopefully by luck of the draw I don't get a crap nightly that breaks something else....

**Comment by endrift** [comment] 2021-03-21 05:44
Yeah, nightlies are always hit or miss. I don't know why it wasn't crashing for me when I used the Play Store version; I think that was just a fluke and I was doing something else wrong. I'm not really sure.

**Comment by Dantasstic** [comment] 2021-03-21 05:46
They clearly need a semi-stable nightly channel. This whole single stable that they stick to for what seems forever at a time, and not being able to know if a nightly you are grabbing is considered more solid than any other.....well, yeah that sucks

**Comment by endrift** [comment] 2021-03-21 06:03
I've filed a PR that will only attempt to initialize the sensors if a game requests them. We'll see if it works--sensors just wholesale don't seem to work on the device I'm testing with for some reason.

**Comment by Dantasstic** [comment] 2021-03-21 07:53
I appreciate your help and your work on this core! 

I have updated to 2021-03-19-RetroArch.apk nightly and it doesn't have the crash issue; whether this build has issues with _anything else_ though remains to be seen haha

**Comment by jdgleaver** [comment] 2021-03-21 12:00
@endrift I am sorry that you wasted your time on this...

When I corrected the bug frontend-side I thought that was sufficient. The Play Store version of RetroArch *is* the latest nightly (well, it is updated three times a week), so anyone running the Play Store version would have had this fixed ages ago.

twinaphex knew I had fixed this buggy code, so I don't know why the issue was reopened... :(

**Comment by twinaphex** [comment] 2021-03-22 08:05
I dont know what went wrong in the communication here, but for what its worth I apologize and am sorry if anyone wasted their time on an issue that was already resolved.
